<a href="https://colab.research.google.com/github/Bhatss/BT---Advanced-Python/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# What is NumPy?
# Why?
# 1. Fixed Type: less bytes
# 2. Contiguous memory

In [ ]:
import numpy as np

In [ ]:
my_arr = np.arange(1_000_000)
print(my_arr)

my_arr2 = my_arr * 2
%timeit my_arr2 = my_arr * 2
print(my_arr2)

[     0      1      2 ... 999997 999998 999999]
1.8 ms ± 203 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
[      0       2       4 ... 1999994 1999996 1999998]


In [ ]:
data = np.array([[1.5, -0.1, 3],[0, -3, 6.5]])
data

array([[ 1.5, -0.1,  3. ],
       [ 0. , -3. ,  6.5]])

In [ ]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [ ]:
#The dimension is according to the number of []. So b is 2d and b1 is 3d.
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)
b1 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(b1)

[[9. 8. 7.]
 [6. 5. 4.]]
3


In [ ]:
# Dimension
print(a.ndim)
print(b.ndim)
print(b1.ndim)

1
2
3


In [ ]:
# shape
print(a.shape)
print(b.shape)
print(b1.shape)

(3,)
(2, 3)
(1, 3, 3)


In [ ]:
# Type!
print(a.dtype)
print(b.dtype)
a.dtype

int64
float64


dtype('int64')

In [ ]:
# size
print(a.itemsize)
print(b.itemsize)

8
8


In [ ]:
import numpy as np
c = np.array([1,2,3], dtype="int64")
print(c.dtype)
print(c.itemsize)

int64
8


In [ ]:
# total size
print(c.size)
print(c.itemsize)

total_size = c.size * c.itemsize
print(total_size)

3
4
12


In [ ]:
d = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(d)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Getting a specific element [row, column]
# How to access number 13
print(d[1, 5])
print(d[1, -2])

13
13


In [ ]:
threed_array = ([])

In [ ]:
#Create a NumPy array from the list [10, 20, 30, 40, 50].
a1 = np.array([10, 20, 30, 40, 50])
print("array:",a1)
a1

array: [10 20 30 40 50]


array([10, 20, 30, 40, 50])

In [ ]:
#Create a 3x3 array of all zeros.
# Only when one row, you do not need more than one []
a2 = np.array([[0,0,0],[0,0,0],[0,0,0]])
print(a2)

a2b = np.zeros((3,3))
print(a2b)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
#Create an array with values ranging from 1 to 10.
#arange is array range, wheras rage is used without module.
#Whenever range is being used, it is exclusive of the last value.
a3 = np.arange(1,11)
print(a3)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
#Create a 4x4 identity matrix.
a4 = np.identity(4)
print(a4, "\n")

a4b = np.eye(4)
print(a4b, "\n")

a4c = np.diag([1,1,1,1])
print(a4c, "\n")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] 

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]] 



In [ ]:
#Create a 2x3 array with random values between 0 and 1.
#Rand automatically chooses between 0 and 1.
a5 = np.random.rand(2,3)
print(a5, "\n")

#Between 10 and 20
a5b = 10 + np.random.rand(2,3) * 10
print(a5b)

[[0.63150794 0.88277012 0.60148481]
 [0.51990309 0.32750407 0.50308328]] 

[[14.15406415 11.06870377 18.12857215]
 [15.15346064 16.59161773 18.16079594]]


In [ ]:
#Reshape the array [1, 2, 3, 4, 5, 6] into a 2x3 matrix.
a6 = np.array([1, 2, 3, 4, 5, 6]).reshape(2,3)
print(a6)

[[1 2 3]
 [4 5 6]]


In [ ]:
#Calculate the mean of the array [10, 20, 30, 40, 50].
a7 = np.array([10, 20, 30, 40, 50]).mean()
print(a7)

30.0


In [ ]:
#Add the arrays [1, 2, 3] and [4, 5, 6] element-wise.
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
a8 = arr1 + arr2
print(a8, "\n")

arr1 = [1, 2, 3]
arr2 = [4, 5, 6]
a8 = np.add(arr1, arr2)
print(a8)



[5 7 9] 

[5 7 9]


In [ ]:
#Multiply two 2x2 matrices: [[1, 2], [3, 4]] and [[5, 6], [7, 8]].
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
a9 = np.matmul(arr3,arr4)
a9b = arr3@arr4
a9c = np.dot(arr3,arr4)
print(arr3, "\n")
print(arr4, "\n")
print(a9, "\n")
print(a9b, "\n")
print(a9c)

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]]


In [ ]:
#Find the maximum value in the array [15, 22, 3, 44, 5].
a10 = np.array([15, 22, 3, 44, 5]).max()
print(a10)

44


In [ ]:
# array
print(np.array([1, 2, 3])) # converts a list to an array.

# asarray
print(np.asarray([1, 2, 3])) # is similar to array, but won't copy if input is already an array.

# arange
print(np.arange(10)) # creates an array with values from 0 to 9.

# ones
print(np.ones((2, 2))) # creates a 2x2 array filled with 1s.

# ones_like
print(np.ones_like(np.array([[1, 2, 3],[4, 5, 6]]))) # creates an array filled with 1s, matching shape of the input.

# zeros
print(np.zeros((2, 2))) # creates a 2x2 array filled with 0s.

# zeros_like
print(np.zeros_like(np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]))) # creates an array of zeros, matching shape of the input.

# empty
print(np.empty((2, 2))) # creates a 2x2 array without initializing entries.

# empty_like
print(np.empty_like(np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]))) # creates an uninitialized array matching shape of the input.

# full
print(np.full((2, 2), 7)) # creates a 2x2 array filled with 7s.

# full_like
print(np.full_like(np.array([1, 2, 3]), 7)) # creates an array filled with 7s, matching shape of input.

# eye
print(np.eye(3)) # creates a 3x3 identity matrix.

# identity
print(np.identity(3)) # creates a 3x3 identity matrix.


[1 2 3]
[1 2 3]
[0 1 2 3 4 5 6 7 8 9]
[[1. 1.]
 [1. 1.]]
[[1 1 1]
 [1 1 1]]
[[0. 0.]
 [0. 0.]]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[0. 0.]
 [0. 0.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[7 7]
 [7 7]]
[7 7 7]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
